# Generated by Django 3.0.6 on 2020-05-21 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_no', models.CharField(max_length=50)),
                ('client_name', models.CharField(max_length=150)),
                ('client_address', models.CharField(max_length=200)),
                ('client_email', models.CharField(max_length=100)),
                ('client_registered', models.DateField()),
                ('client_active', models.BooleanField(default=False)),
                ('client_ip', models.CharField(default='0.0.0.0', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_date', models.DateField(auto_now_add=True)),
                ('status_time', models.TimeField(auto_now_add=True)),
                ('status_note', models.CharField(max_length=200)),
                ('status_type', models.CharField(choices=[('OFFLINE', 'Offline'), ('TIMED-OUT', 'Time out'), ('INTERMITENT', 'Intermitent'), ('ONLINE', 'Online')], default='OFFLINE', max_length=11)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Client')),
            ],
            options={
                'verbose_name': 'status',
                'verbose_name_plural': 'statuses',
                'ordering': ['-status_date'],
            },
        ),
        migrations.AddIndex(
            model_name='status',
            index=models.Index(fields=['status_date'], name='client_stat_status__b0b815_idx'),
        ),
    ]
