# Generated by Django 3.0.6 on 2020-05-30 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.IntegerField()),
                ('bill_date', models.DateField()),
                ('bill_period_01', models.DateField()),
                ('bill_period_02', models.DateField()),
                ('bill_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('bill_note', models.CharField(max_length=254)),
                ('bill_cancelled', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='client.Client')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_no', models.IntegerField()),
                ('receipt_date', models.DateField()),
                ('receipt_date_01', models.DateField(auto_now_add=True)),
                ('receipt_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('receipt_cancelled', models.BooleanField(default=False)),
                ('receipt_type', models.CharField(choices=[('CASH', 'Cash'), ('CHEQUE', 'Cheque'), ('OTHERS', 'Others')], default='CASH', max_length=6)),
                ('receipt_note', models.CharField(max_length=254)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='client.Bill')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
