# Generated by Django 3.0.6 on 2020-05-30 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_bill_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'ordering': ['-bill_date'], 'verbose_name': 'billing', 'verbose_name_plural': 'billings'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-receipt_date'], 'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
    ]
