# Generated by Django 3.0.6 on 2020-05-30 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_payment_receipt_cheque_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpensesType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expenses_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expenses_date', models.DateTimeField()),
                ('expenses_refno', models.CharField(blank=True, max_length=50)),
                ('expenses_amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('expenses_purpose', models.CharField(max_length=254)),
                ('expenses_note', models.CharField(max_length=100)),
                ('expenses_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses_types', to='client.ExpensesType')),
            ],
        ),
    ]
