# Generated by Django 3.0.7 on 2020-06-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_expenses_expensestype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ('client_name', 'client_no'), 'verbose_name': 'client', 'verbose_name_plural': 'clients'},
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['client_no', 'client_name'], name='client_clie_client__6e8efb_idx'),
        ),
    ]
