# Generated by Django 3.0.7 on 2020-06-20 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_auto_20200620_1609'),
        ('client', '0006_client_client_contact'),
    ]

    operations = [
    ]
