# Generated by Django 3.0.7 on 2020-06-20 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_merge_20200620_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_contact_person',
            field=models.CharField(default='', max_length=100),
        ),
    ]
