# Generated by Django 3.0.7 on 2020-06-20 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_client_client_contact_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_contact',
            field=models.CharField(default='', max_length=50),
        ),
    ]
